platform :ios, 10.0

use_frameworks!
inhibit_all_warnings!

target "efficacious" do
pod 'SwiftHEXColors' 
pod 'DDTRepeater'
pod 'Onboard'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Crash'
pod 'MBProgressHUD'
pod 'TSMessages'
pod 'HELargeCenterTabBarController'

end

