use_frameworks!

target "Pomodoroban" do
pod 'SwiftHEXColors'
pod 'Fabric'
pod 'Crashlytics'
pod 'LSRepeater'
pod 'Onboard'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'MBProgressHUD'
pod 'TSMessages'

end

