use_frameworks!

target "Pomodoroban" do
pod 'SwiftHEXColors' , '1.0.4'
pod 'LSRepeater'
pod 'Onboard'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Crash'
pod 'MBProgressHUD'
pod 'TSMessages'
pod 'EasyTipView' , '= 1.0.1'

end

